### ISSUE TITLE
[Feat] 예약 엔터티 작성

### ISSUE THREAD

**Issue by jellyyelly** [codesquad-masters2024-be-airdnb-team04/be-airdnb#6]
**개발할 기능 설명**
- 숙소 예약 엔터티 클래스를 작성합니다.

---

**TODO**
- [ ] 한 명의 회원이 여러 예약을 할 수 있다.
- [ ] 한 숙소는 여러 번 예약될 수 있다.
- [ ] 체크인/체크아웃 시간을 `연-월-일 시:분:초` 로 알 수 있다.
- [ ] 총 요금을 계산할 수 있다.
- [ ] 예약된 시간을 `연-월-일 시:분:초` 로 알 수 있다.
- [ ] 예약 상태를 알 수 있다.
  - [ ] 예약 상태는 예약 대기, 예약 확정, 예약 취소 단계로 구분된다.
